kind: Deployment
apiVersion: apps/v1
metadata:
  name: climatewavers
  labels:
    app: climatewavers
    sandbox: olagoldhackxx
    sandbox-olagoldhackxx: climatewavers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: climatewavers
  template:
    metadata:
      labels:
        app: climatewavers
    spec:
      imagePullSecrets:
        - name: quay-registry-secret
      containers:
        - name: climatewavers
          image: quay.io/olagoldhackxx/climatewavers:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
              protocol: TCP
