apiVersion: v1
kind: Service
metadata:
  labels:
    app: climatewavers
    sandbox: olagoldhackxx
    olagoldhackxx: climatewavers
  name: climatewavers
spec:
  ports:
  - name: 8000-tcp
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: climatewavers
  sessionAffinity: None
  type: ClusterIP