apiVersion: v1
kind: Service
metadata:
  name: climatewavers-mariadb
spec:
  selector:
    app: climatewavers-mariadb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP