apiVersion: apps/v1

kind: Deployment

metadata:

  name: climatewavers-mariadb

  labels:

    sandbox: climatewavers

    climatewavers: climatewavers-mariadb

spec:

  selector:

    matchLabels:

      app: mariadb

      tier: database

  template:

    metadata:

      labels:

        app: mariadb

        tier: database

    spec:

      containers:

      - name: mariadb

        env:

        - name: MARIADB_ROOT_PASSWORD
          value: waverx

        image: mariadb

        resources:

          limits:

            memory: "512Mi"

            cpu: "500m"

        ports:

        - containerPort: 3306

        volumeMounts:

        - name: mariadbvolume

          mountPath: /var/lib/mariadb

      volumes:

       - name: mariadbvolume

         persistentVolumeClaim:

           claimName: mariadbvolume