kind: Deployment
apiVersion: apps/v1
metadata:
  name: climatewavers-chatbot
  labels:
    app: climatewavers-chatbot
    sandbox: olagoldhackxx
    sandbox-olagoldhackxx: climatewavers-chatbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: climatewavers-chatbot
  template:
    metadata:
      labels:
        app: climatewavers-chatbot
    spec:
      imagePullSecrets:
        - name: quay-registry-secret
      containers:
        - name: climatewavers-chatbot
          image: quay.io/olagoldhackxx/climatewavers:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
