---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: notification-system
    app.kubernetes.io/component: notification-system
    app.kubernetes.io/instance: notification-system
    app.kubernetes.io/name: notification-system
  name: notification-system
spec:
  replicas: 1
  selector:
    app: notification-system
  template:
    metadata:
      labels:
        app: notification-system
    spec:
      containers:
        - image: quay.io/olagoldhackxx/notification-system:v1
          imagePullPolicy: Always
          name: notification-system
          ports:
            - containerPort: 3002
              protocol: TCP