---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: waverx-nlp
    app.kubernetes.io/component: waverx-nlp
    app.kubernetes.io/instance: waverx-nlp
    app.kubernetes.io/name: waverx-nlp
    app.kubernetes.io/part-of: models
  name: waverx-nlp
spec:
  replicas: 1
  selector:
    app: waverx-nlp
  template:
    metadata:
      labels:
        app: waverx-nlp
    spec:
      containers:
        - image: quay.io/olagoldhackxx/waverx-nlp:v1
          imagePullPolicy: Always
          name: waverx-nlp
          ports:
            - containerPort: 8000
              protocol: TCP