kind: Deployment
apiVersion: apps/v1
metadata:
  name: climatewavers-djangobackend
  labels:
    app: climatewavers-djangobackend
    sandbox: olagoldhackxx
    sandbox-olagoldhackxx: climatewavers-djangobackend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: climatewavers-djangobackend
  template:
    metadata:
      labels:
        app: climatewavers-djangobackend
    spec:
      imagePullSecrets:
        - name: quay-registry-secret
      containers:
        - name: climatewavers-djangobackend
          image: quay.io/olagoldhackxx/climatewavers-djangobackend:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
              protocol: TCP
