---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tweetchatbot
    app.kubernetes.io/component: tweetchatbot
    app.kubernetes.io/instance: tweetchatbot
    app.kubernetes.io/name: tweetchatbot
    app.kubernetes.io/part-of: bots
    app.openshift.io/runtime-namespace: climatewavers-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tweetchatbot
  template:
    metadata:
      labels:
        app: tweetchatbot
        deployment: tweetchatbot
    spec:
      containers:
        - image: quay.io/olagoldhacxx/tweetchatbot:v1
          name: tweetchatbot
          ports:
            - containerPort: 3000
              protocol: TCP