---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tweetbot
    app.kubernetes.io/component: tweetbot
    app.kubernetes.io/instance: tweetbot
    app.kubernetes.io/name: tweetbot
    app.kubernetes.io/part-of: bots
    app.openshift.io/runtime-namespace: climatewavers-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tweetbot
  template:
    metadata:
      labels:
        app: tweetbot
        deployment: tweetbot
    spec:
      containers:
        - image: quay.io/olagoldhacxx/tweetbot:v1
          name: tweetbot
          ports:
            - containerPort: 3000
              protocol: TCP