---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: oauth
    app.kubernetes.io/component: oauth
    app.kubernetes.io/instance: oauth
    app.kubernetes.io/name: oauth
  name: oauth
spec:
  replicas: 1
  selector:
    app: oauth
  template:
    metadata:
      labels:
        app: oauth
    spec:
      containers:
        - image: quay.io/olagoldhackxx/oauth:v1
          imagePullPolicy: Always
          name: oauth
          ports:
            - containerPort: 8000
              protocol: TCP