apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f kafka-docker-compose.yaml
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: kafka
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kafka
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f kafka-docker-compose.yaml
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/kafkaquickstart: "true"
        io.kompose.service: kafka
    spec:
      containers:
        - args:
            - sh
            - -c
            - bin/kafka-server-start.sh config/server.properties --override listeners=$(){KAFKA_LISTENERS} --override advertised.listeners=$(){KAFKA_ADVERTISED_LISTENERS} --override zookeeper.connect=$(){KAFKA_ZOOKEEPER_CONNECT}
          env:
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://kafka:9092
            - name: KAFKA_LISTENERS
              value: PLAINTEXT://:9092, OUTSIDE://:9094
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper:2181
            - name: LOG_DIR
              value: /tmp/logs
          image: quay.io/strimzi/kafka:0.23.0-kafka-2.8.0
          name: kafka
          ports:
            - containerPort: 9092
              hostPort: 9092
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
