---
apiVersion: intel.com/v1alpha1
kind: ModelServer
metadata:
  name: waverx-vision
spec:
  models_repository:
    models_volume_claim: waverx-vision-pvc
  models_settings:
    low_latency_transformation: true
    max_sequence_number: 0
    model_name: waverx-vision
    model_path: /opt/models/quantized_model
    single_model_mode: true
    target_device: CPU
  server_settings:
    file_system_poll_wait_seconds: 0
    grpc_workers: 1
    log_level: INFO
    rest_workers: 3
    sequence_cleaner_poll_wait_minutes: 0
  service_parameters:
    grpc_port: 8080
    rest_port: 8081
    service_type: ClusterIP