apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: source-pvc
  labels:
    sandbox: pipelines
    pipelines: workspace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
