---
apiVersion: v1
kind: Pod
metadata:
  name: temp-pod
spec:
  containers:
    - command: ["/bin/sh"]
      image: quay.io/olagoldhackxx/waverx-vision:v1
      name: debug-container
      stdin: true
      tty: true
      volumeMounts:
        - mountPath: /opt/models
          name: data-volume
  volumes:
    - name: data-volume
      persistentVolumeClaim:
        claimName: waverx-vision-pvc