---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: oauth
    app.kubernetes.io/component: oauth
    app.kubernetes.io/instance: oauth
    app.kubernetes.io/name: oauth
  name: oauth
spec:
  port:
    targetPort: 8000-tcp
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: oauth