apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: climatewavers-chatbot
    sandbox: olagoldhackxx
    olagoldhackxx: climatewavers-chatbot
  name: climatewavers-chatbot
spec:
  port:
    targetPort: 80-tcp
  to:
    kind: Service
    name: climatewavers-chatbot
