---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: tweetchatbot
    app.kubernetes.io/component: tweetchatbot
    app.kubernetes.io/instance: tweetchatbot
    app.kubernetes.io/name: tweetchatbot
  name: tweetchatbot
spec:
  port:
    targetPort: 3001-tcp
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: tweetchatbot