apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: climatewavers-backend
    sandbox: olagoldhackxx
    olagoldhackxx: climatewavers-backend
  name: climatewavers-backend
spec:
  port:
    targetPort: 80-tcp
  to:
    kind: Service
    name: climatewavers-backend
