apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: climatewavers-djangobackend
    sandbox: olagoldhackxx
    olagoldhackxx: climatewavers-djangobackend
  name: climatewavers-djangobackend
spec:
  port:
    targetPort: 8000-tcp
  to:
    kind: Service
    name: climatewavers-djangobackend
