---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: tweetbot
    app.kubernetes.io/component: tweetbot
    app.kubernetes.io/instance: tweetbot
    app.kubernetes.io/name: tweetbot
  name: tweetbot
spec:
  port:
    targetPort: 3001-tcp
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: tweetbot