---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: notification-system
    app.kubernetes.io/component: notification-system
    app.kubernetes.io/instance: notification-system
    app.kubernetes.io/name: notification-system
  name: notification-system
spec:
  port:
    targetPort: 3002-tcp
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: notification-system