apiVersion: v1
kind: Service
metadata:
  labels:
    app: climatewavers-djangobackend
    sandbox: olagoldhackxx
    olagoldhackxx: climatewavers-djangobackend
  name: climatewavers-djangobackend
spec:
  ports:
  - name: 8000-tcp
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: climatewavers-djangobackend
  sessionAffinity: None
  type: ClusterIP