---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: tweetchatbot
    app.kubernetes.io/component: tweetchatbot
    app.kubernetes.io/instance: tweetchatbot
    app.kubernetes.io/name: tweetchatbot
  name: tweetchatbot
spec:
  ports:
    - name: 3001-tcp
      port: 3001
      protocol: TCP
      targetPort: 3001
  selector:
    app: tweetchatbot
  sessionAffinity: None
  type: ClusterIP
  wildcardPolicy: None