apiVersion: v1
kind: Service
metadata:
  labels:
    app: climatewavers-backend
    sandbox: olagoldhackxx
    olagoldhackxx: climatewavers-backend
  name: climatewavers-backend
spec:
  ports:
  - name: 8000-tcp
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: climatewavers-backend
  sessionAffinity: None
  type: ClusterIP