---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend
    app.kubernetes.io/component: backend
    app.kubernetes.io/instance: backend
    app.kubernetes.io/name: backend
  name: backend
spec:
  ports:
    - name: 443-tcp
      port: 443
      protocol: TCP
      targetPort: 443
  selector:
    app: backend
  sessionAffinity: None
  type: ClusterIP