---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: notification-system
    app.kubernetes.io/component: notification-system
    app.kubernetes.io/instance: notification-system
    app.kubernetes.io/name: notification-system
  name: notification-system
spec:
  ports:
    - name: 3002-tcp
      port: 3002
      protocol: TCP
      targetPort: 3002
  selector:
    app: notification-system
  sessionAffinity: None
  type: ClusterIP
  wildcardPolicy: None