apiVersion: v1
kind: Service
metadata:
  labels:
    app: oauth
    app.kubernetes.io/component: oauth
    app.kubernetes.io/instance: oauth
    app.kubernetes.io/name: oauth
  name: oauth
spec:
  ports:
  - name: 8000-tcp
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: oauth
  sessionAffinity: None
  type: ClusterIP