---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: waverx-analysis
    app.kubernetes.io/component: waverx-analysis
    app.kubernetes.io/instance: waverx-analysis
    app.kubernetes.io/name: waverx-analysis
  name: waverx-analysis
spec:
  ports:
    - name: 6000-tcp
      port: 6000
      protocol: TCP
      targetPort: 6000
  selector:
    app: waverx-analysis
  sessionAffinity: None
  type: ClusterIP