apiVersion: v1
kind: Service
metadata:
  labels:
    app: climatewavers-chatbot
    sandbox: olagoldhackxx
    olagoldhackxx: climatewavers-chatbot
  name: climatewavers-chatbot
spec:
  ports:
  - name: 80-tcp
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: climatewavers-chatbot
  sessionAffinity: None
  type: ClusterIP