apiVersion: v1
kind: Service
metadata:
  labels:
    app: climatewavers
    sandbox: olagoldhackxx
    olagoldhackxx: climatewavers
  name: climatewavers
spec:
  ports:
  - name: 80-tcp
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: climatewavers
  sessionAffinity: None
  type: ClusterIP