---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend
    app.kubernetes.io/component: backend
    app.kubernetes.io/instance: backend
    app.kubernetes.io/name: backend
  name: backend
spec:
  ports:
    - name: 5173-tcp
      port: 5173
      protocol: TCP
      targetPort: 5173
  selector:
    app: backend
  sessionAffinity: None
  type: ClusterIP