---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: waverx-nlp
    app.kubernetes.io/component: waverx-nlp
    app.kubernetes.io/instance: waverx-nlp
    app.kubernetes.io/name: waverx-nlp
  name: waverx-nlp
spec:
  ports:
    - name: 5000-tcp
      port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app: waverx-nlp
  sessionAffinity: None
  type: ClusterIP
  wildcardPolicy: None