---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: chat-interface
    app.kubernetes.io/component: chat-interface
    app.kubernetes.io/instance: chat-interface
    app.kubernetes.io/name: chat-interface
  name: chat-interface
spec:
  ports:
    - name: 3003-tcp
      port: 3003
      protocol: TCP
      targetPort: 3003
  selector:
    app: chat-interface
  sessionAffinity: None
  type: ClusterIP