apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f kafka-docker-compose.yaml
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: zookeeper
  name: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: zookeeper
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f kafka-docker-compose.yaml
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/kafkaquickstart: "true"
        io.kompose.service: zookeeper
    spec:
      containers:
        - args:
            - sh
            - -c
            - bin/zookeeper-server-start.sh config/zookeeper.properties
          env:
            - name: LOG_DIR
              value: /tmp/logs
          image: quay.io/strimzi/kafka:0.23.0-kafka-2.8.0
          name: zookeeper
          ports:
            - containerPort: 2181
              hostPort: 2181
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
