# Generated by Django 3.2.8 on 2023-11-19 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate_wavers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='comment_count',
            new_name='comments_count',
        ),
        migrations.AddField(
            model_name='post',
            name='likers_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='savers_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
