# Generated by Django 3.2.8 on 2023-11-07 00:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('climate_wavers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=150, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customtoken',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=150, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='follower',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=150, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=150, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=150, primary_key=True, serialize=False),
        ),
    ]
