# Generated by Django 3.2.8 on 2023-10-29 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate_wavers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtoken',
            name='refresh_token',
            field=models.CharField(max_length=2048),
        ),
    ]
