# Generated by Django 3.2.8 on 2023-11-07 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate_wavers', '0002_auto_20231106_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtoken',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
