# Generated by Django 3.2.8 on 2023-10-29 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate_wavers', '0002_alter_customtoken_refresh_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.BinaryField(max_length=255, null=True),
        ),
    ]
