# Generated by Django 3.2.8 on 2023-11-19 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('climate_wavers', '0002_auto_20231119_0647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comments_count',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likers_count',
        ),
        migrations.RemoveField(
            model_name='post',
            name='savers_count',
        ),
    ]
