# Generated by Django 3.2.8 on 2023-11-07 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate_wavers', '0003_customtoken_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cover',
            field=models.ImageField(blank=True, max_length=300, null=True, upload_to='covers/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, max_length=300, null=True, upload_to='profile_pic/'),
        ),
    ]
