# Generated by Django 3.2.8 on 2023-10-30 15:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('climate_wavers', '0004_auto_20231030_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtoken',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
