# Generated by Django 3.2.8 on 2023-11-02 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('climate_wavers', '0005_alter_customtoken_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='content_image',
            field=models.ImageField(blank=True, null=True, upload_to='comment/'),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcomments', to='climate_wavers.comment'),
        ),
    ]
