# Generated by Django 3.0.2 on 2023-10-12 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate_wavers', '0019_auto_20231012_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
