# Generated by Django 3.0.2 on 2023-10-12 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('climate_wavers', '0020_user_last_location'),
        ('climate_wavers', '0019_auto_20231012_2048'),
    ]

    operations = [
    ]
