# Generated by Django 3.0.2 on 2023-10-12 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate_wavers', '0021_merge_20231012_2334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='user',
            name='longitude',
        ),
        migrations.AddField(
            model_name='user',
            name='last_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
