kind: Deployment
apiVersion: apps/v1
metadata:
  name: waverX-Analysis
  labels:
    app: waverX-Analysis
    sandbox: olagoldhackxx
    sandbox-olagoldhackxx: waverX-Analysis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: waverX-Analysis
  template:
    metadata:
      labels:
        app: waverX-Analysis
    spec:
      imagePullSecrets:
        - name: quay-registry-secret
      containers:
        - name: waverX-Analysis
          image: quay.io/olagoldhackxx/climatewavers-waverX-Analysis:v1:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8400
              protocol: TCP
